spring:
  address: localhost
  data:
    mongodb:
      uri: mongodb://user:pass@localhost:27017/healdb?authSource=admin
      uuid-representation: standard
server:
  port: 8081

client:
  user:
    base-url: "http://localhost:8080"
    doctor-path: "/api/v1/doctors"

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG