spring:
  data:
    mongodb:
      uri: mongodb://MongoECSUser:Helucipass745@ecsmongodb.cluster-cqunz6ixnkor.ap-southeast-1.docdb.amazonaws.com:27017/healdb?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      uuid-representation: standard

client:
  user:
    base-url: "http://apploadbalancer-1721504831.ap-southeast-1.elb.amazonaws.com:80"
    doctor-path: "/api/v1/doctors"

secEnvConf:
  enableLoginGuard: true
