spring:
  data:
    mongodb:
      uri: mongodb://LotusFlower:Logiti857@ecsmongodb.cluster-cqunz6ixnkor.ap-southeast-1.docdb.amazonaws.com:27017/healdb?authSource=admin&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      uuid-representation: standard

secEnvConf:
  enableLoginGuard: true
